# Generated by Django 5.1.7 on 2026-05-04 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_premiumsubscription_stripe_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumsubscription',
            name='stripe_checkout_session_id',
        ),
        migrations.RemoveField(
            model_name='premiumsubscription',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='premiumsubscription',
            name='stripe_subscription_id',
        ),
    ]
