# Generated by Django 5.1.7 on 2026-05-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorrequest',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=5),
        ),
        migrations.AddField(
            model_name='mentorrequest',
            name='price_at_request',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='mentor_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='mentor_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
