# Generated by Django 5.1.7 on 2026-05-29 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_mentorrequest_offered_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(max_length=120)),
                ("tag", models.CharField(max_length=80)),
                ("event_date", models.DateField()),
                ("is_online", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["event_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunityThread",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("topic", models.CharField(max_length=255)),
                ("stats_label", models.CharField(blank=True, max_length=120)),
                ("signal_label", models.CharField(blank=True, max_length=80)),
                ("is_featured", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_threads",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
