# Generated by Django 5.1.7 on 2026-05-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_communityevent_communitythread"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorrequest",
            name="meeting_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentorrequest",
            name="user_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
